#!/usr/bin/env bash
# SG 데모 올인원 스타터
#   1. OpenClaw 게이트웨이 시작 또는 재시작 (fetch 인터셉터 반영)
#   2. Sentinel ingest 백그라운드 시작 (OPENCLAW_* 환경변수가 있을 때)
#   3. security-viz Vite 개발 서버 시작
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

if ! command -v python3 >/dev/null 2>&1; then
  echo "[run-viz] python3 is required." >&2; exit 1
fi
if ! command -v npm >/dev/null 2>&1; then
  echo "[run-viz] npm is required." >&2; exit 1
fi
if ! command -v openclaw >/dev/null 2>&1; then
  echo "[run-viz] openclaw is required." >&2; exit 1
fi

PY="python3"
if [[ -x "$ROOT/.venv/bin/python" ]]; then
  PY="$ROOT/.venv/bin/python"
fi

PIDS=()
cleanup() {
  local p
  for p in "${PIDS[@]:-}"; do
    kill "$p" 2>/dev/null || true
  done
}
trap cleanup EXIT INT TERM HUP

# ── 1. OpenClaw 게이트웨이 시작 / 재시작 ────────────────────────────────────
echo "" >&2
echo "[run-viz] ── 1. OpenClaw 게이트웨이 ──────────────────────────────" >&2
if openclaw gateway status 2>/dev/null | grep -q "RPC probe: ok"; then
  echo "[run-viz] 게이트웨이 실행 중 → 재시작 (fetch 인터셉터 적용)…" >&2
  openclaw gateway restart >&2
else
  echo "[run-viz] 게이트웨이 꺼져 있음 → 시작…" >&2
  openclaw gateway start >&2
fi

# 게이트웨이가 준비될 때까지 대기 (최대 15초)
echo "[run-viz] 게이트웨이 준비 대기…" >&2
for i in $(seq 1 15); do
  if openclaw gateway status 2>/dev/null | grep -q "RPC probe: ok"; then
    echo "[run-viz] 게이트웨이 준비 완료 (${i}s)" >&2
    break
  fi
  sleep 1
  if [[ $i -eq 15 ]]; then
    echo "[run-viz] 경고: 게이트웨이 준비 확인 실패 — 계속 진행합니다." >&2
  fi
done

# ── 2. Sentinel ingest ───────────────────────────────────────────────────────
echo "" >&2
echo "[run-viz] ── 2. Sentinel ingest ────────────────────────────────────" >&2
if [[ -n "${OPENCLAW_GATEWAY_WS_URL:-}" ]]; then
  UFILE="$ROOT/security-viz/.env.development.local"
  {
    echo "# Generated by run-viz.sh — not committed"
    printf "VITE_SG_GATEWAY_WS_URL=%s\n" "${OPENCLAW_GATEWAY_WS_URL}"
    printf "VITE_SG_SESSION_KEY=%s\n" "${OPENCLAW_GATEWAY_SESSION_KEY:-agent:main}"
  } >"$UFILE"
  echo "[run-viz] .env.development.local 작성 완료." >&2
else
  rm -f "$ROOT/security-viz/.env.development.local" 2>/dev/null || true
fi

if [[ -n "${OPENCLAW_GATEWAY_WS_URL:-}" && -n "${OPENCLAW_GATEWAY_TOKEN:-}" ]]; then
  echo "[run-viz] Sentinel ingest 시작 → scripts/sentinel/data/trace.jsonl" >&2
  PYTHONPATH="$ROOT/scripts" "$PY" "$ROOT/scripts/sentinel/ingest.py" --duration-s 0 &
  PIDS+=("$!")
else
  echo "[run-viz] Sentinel ingest 생략 (OPENCLAW_GATEWAY_WS_URL + TOKEN 필요)" >&2
fi

# ── 3. security-viz Vite 개발 서버 ─────────────────────────────────────────
echo "" >&2
echo "[run-viz] ── 3. security-viz 시작 ──────────────────────────────────" >&2
cd "$ROOT/security-viz"
if [[ ! -d node_modules ]]; then
  echo "[run-viz] npm install (최초 실행)…" >&2
  npm install
fi

echo "" >&2
echo "[run-viz] Ctrl+C 로 Vite + ingest 종료." >&2
echo "" >&2

npm run dev
