#!/usr/bin/env bash
# After OpenClaw gateway is up: security-viz (Vite) + optional Sentinel ingest → trace.jsonl.
#
# Recommended: OPENCLAW_GATEWAY_WS_URL, OPENCLAW_GATEWAY_TOKEN, OPENCLAW_GATEWAY_SESSION_KEY
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

if ! command -v python3 >/dev/null 2>&1; then
  echo "run-viz.sh: python3 is required (Sentinel ingest when OPENCLAW_* is set)." >&2
  exit 1
fi
if ! command -v npm >/dev/null 2>&1; then
  echo "run-viz.sh: npm is required." >&2
  exit 1
fi

PY="python3"
if [[ -x "$ROOT/.venv/bin/python" ]]; then
  PY="$ROOT/.venv/bin/python"
fi

PIDS=()
cleanup() {
  local p
  for p in "${PIDS[@]:-}"; do
    kill "$p" 2>/dev/null || true
  done
}
trap cleanup EXIT INT TERM HUP

if [[ -n "${OPENCLAW_GATEWAY_WS_URL:-}" ]]; then
  UFILE="$ROOT/security-viz/.env.development.local"
  {
    echo "# Generated by run-viz.sh — not committed (see .gitignore)"
    printf "VITE_SG_GATEWAY_WS_URL=%s\n" "${OPENCLAW_GATEWAY_WS_URL}"
    printf "VITE_SG_SESSION_KEY=%s\n" "${OPENCLAW_GATEWAY_SESSION_KEY:-agent:main}"
  } >"$UFILE"
  echo "[run-viz] wrote $UFILE (WS URL + session preset)." >&2
else
  rm -f "$ROOT/security-viz/.env.development.local" 2>/dev/null || true
fi

if [[ -n "${OPENCLAW_GATEWAY_WS_URL:-}" && -n "${OPENCLAW_GATEWAY_TOKEN:-}" ]]; then
  echo "[run-viz] Sentinel ingest → scripts/sentinel/data/trace.jsonl …" >&2
  PYTHONPATH="$ROOT/scripts" "$PY" "$ROOT/scripts/sentinel/ingest.py" --duration-s 0 &
  PIDS+=("$!")
else
  echo "[run-viz] Sentinel ingest skipped (set OPENCLAW_GATEWAY_WS_URL + TOKEN to log trace.jsonl)." >&2
fi

cd "$ROOT/security-viz"
if [[ ! -d node_modules ]]; then
  echo "[run-viz] npm install (first run) …" >&2
  npm install
fi

echo "" >&2
echo "[run-viz] Open the URL below. Paste gateway token → Connect." >&2
echo "[run-viz] Messages & tools for the session appear in the viz; ingest mirrors events to trace.jsonl when enabled." >&2
echo "[run-viz] Ctrl+C stops Vite and ingest." >&2
echo "" >&2

npm run dev
